### ISSUE TITLE
Roadmap – 0.16

### ISSUE THREAD

**Issue by d4rkr00t** [d4rkr00t/aik#297]
I've decided to publish a roadmap for every upcoming release. Roadmap is a subject to 

- 🛠 – internal
- 🔎 – spike 

----------

- [x] Don't show annoying warning about react if it's already been installed
- [x] Fix error messages for webpack 2
- [x] Cleanup messages
- [x] Investigate cache-loader 🔎
- [x] Generate/Update package.json
- [x] Investigate suppress warning 🔎
- [x] Add Jest test for cli output 🛠
- [x] Fix Node 4 build – https://github.com/MoOx/eslint-loader/pull/178
- [x] Investigate html minification 🔎
- [x] Investigate ngrok + hot reload issue 🔎
- [x] Test with npm 5 🛠
- [x] Visual Regression Testing 🛠 🔎
