### ISSUE TITLE
Release 0.17

### ISSUE THREAD

**Issue by d4rkr00t** [d4rkr00t/aik#307]
Frameworks support release.

- [x] Webpack 3
- [x] Auto detect that project uses react and reload webpack-dev-server
- [x] Add support for static methods and props also for instances methods and props
- [x] Pick up custom .babelrc (?)
