### ISSUE TITLE
Release 0.18

### ISSUE THREAD

**Issue by d4rkr00t** [d4rkr00t/aik#315]
### Tech dept release.

- [ ] ESM Modules
- [ ] Drop node < 8
- [ ] Change tool for visreg
- [ ] Use saucelabs or browserstack for visreg tests
- [ ] ~100% test coverage
- [ ] Syntax highlight package.json
- [ ] More Examples
